name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # NOTE: You should use the checkout action any time your workflow will
      # run against the repository's code.
      # See: https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v3
      # NOTE: Github runners have native support for Node.js 12 and Node.js 16.
      - name: "Install dependencies"
        run: |
          npm install
      - name: "Run all package scripts"
        run: |
          # See package.json for commands.
          npm run all
  # Ensure the custom action works on a clean runner without building.
  test-usage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      uses: ./ # Uses an action in the root directory.
        with:
          input: "This is some input."
